#!/bin/bash
#
# mksttvenvgpu - make a virtual environment for speech to text (STT) on a GPU 
# The GPU suffix adds installing Nvidia wheel files for PyTorch, torchaudio and torchvision
# It requires a functioning /usr/bin/python3.10 
#
#+--------------------------------------------------------------------------+
function runCmd
# run a command and exit if it fails
#+--------------------------------------------------------------------------+
 {
  : SOURCE: ${BASH_SOURCE}
  : STACK:  ${FUNCNAME[@]}

  cmd="$@"                                 # all args

  echo " "
  echo "Running: $cmd" | tee -a $logFile
  eval $cmd 2>&1 | tee -a $logFile
  rc=$?
  if [ "$rc" != 0 ]; then                  # it failed
    echo "ERROR: $cmd returned $rc" | tee -a $logFile
    exit 1
  else
    echo "Command was successful!" | tee -a $logFile
  fi
 }                                         # runCmd()

function makeVenv                          # make the virtual environment
 {
  set -e
  if [ ! -d $HOME ]; then 
    echo "ERROR: no home directory found at $HOME"
    exit 1
  fi
  theVenv="$HOME/stt_venv"
  if [ -d $theVenv ]; then                 # virtual environment exists
    echo "ERROR: virtual environment already exists - to delete it run:"
    echo "rm -fr $theVenv"
    exit 2
  fi
  cd $HOME                                 # build in home directory
  
  echo "Installing co-reqs for a virtual environment..."
  # runCmd sudo apt-get -qq install -y python3.10-venv
  # runCmd sudo apt-get -qq install -y python3.10-dev
  # runCmd sudo apt-get -qq install -y build-essential
  # runCmd sudo apt-get -qq install -y portaudio19-dev
  
  echo "Creating virtual environment at $theVenv"
  runCmd /usr/bin/python3 -m venv $theVenv     # create a 3.10 venv
  source $theVenv/bin/activate             # activate venv
  local pipCmd="$theVenv/bin/pip"          # use the newly created pip
  echo "Installing STT requirements ..."
  runCmd $pipCmd install --upgrade pip wheel
  echo "Installing numpy 1.x ..."          # numpy 2.x conflicts with other libraries
  $pipCmd install "numpy<2.0" | tee -a $logFile 
  echo "Installing PyAudio ..."
  runCmd $pipCmd install PyAudio 
  echo "Installing PyTorch ..."
  runCmd $pipCmd install torch==2.8.0 --index-url https://download.pytorch.org/whl/cu126 --pre --extra-index-url https://pypi.jetson-ai-lab.io/jp6/cu126
  echo "Installing torchaudio ..."
  runCmd $pipCmd install torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu126 --pre --extra-index-url https://pypi.jetson-ai-lab.io/jp6/cu126
  echo "Installing torchvision ..."
  runCmd $pipCmd install torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cu126 --pre --extra-index-url https://pypi.jetson-ai-lab.io/jp6/cu126
  echo "Installing Whisper ..."
  runCmd $pipCmd install git+https://github.com/openai/whisper.git
  runCmd $pipCmd install whisper 
 }

# main 
timeStamp=`date +"%y-%m-%d-%H-%M-%S"`
logFile="$HOME/$timeStamp-install1.out"    # output file
echo "Running $0 on $timeStamp to make venv ..." > $logFile # create a new log file
makeVenv
