#!/bin/bash
#
# grm - short command to search through Minimy python files 
#
cd $HOME/minimy
frameworkFiles="framework/*py framework/*/*py framework/*/*/*py framework/*/*/*/*py framework/*/*/*/*/*py framework/*/*/*/*/*/*py framework/*/*/*/*/*/*/*py"
srcFiles="*py bus/*py $frameworkFiles skills/*py skills/*/*py skills/*/*/*py"
grep -n "$@" $srcFiles 2>/dev/null | sed "s:^:$HOME/minimy/:g"
