- Advanced:
    CrappyAEC: n
    InputDeviceId: '0'
    InputLevelControlName: Mic
    LogLevel: d
    NLP:
      UseRemote: n
    OutputDeviceName: ''
    OutputLevelControlName: Speaker
    Platform: u
    STT:
      UseRemote: n
    TTS:
      Local: p
      Remote: p
      UseRemote: n
      LocalVoice: en_US-hfc_male-medium
  Basic:
    AWSId: ''
    AWSKey: ''
    BaseDir: /home/pi/minimy
    GoogleApiKeyPath: install/my_google_key.json
    Hub: localhost
    MusicDir: /mnt/usb/music
    WakeWords: 
    - 'computer'
    - 'internet'
