#!/bin/bash
#
# stopminimy - kill processes with 'minimy' in them, sort log files, copy to $HOME and unmount tmpfs
#
# main() 
echo "Stopping Minimy ..." 
procs=`ps -ef | egrep 'minimy/skills|skills/system_skills|framework/services|MsgBus|mimic3|skill_system.py' | grep -v grep`
if [ ${#procs} = 0 ]; then 
  echo "Minimy does not appear to be running"
else
  echo "$procs" | while read nextProc; do
    pid=`echo $nextProc | awk '{print $2}'`
    echo "killing process: $nextProc ..."
    sudo kill $pid
  done 
fi
sortlogs                                   # create a time sorted file of all logs
rm -fr /tmp/pymp*                          # clean up socket temp directories
cd $HOME
cp $HOME/minimy/logs/* $HOME               # copy each log file   
sleep 3                                    # wait for processes to die before unmounting tmpfs
sudo umount $HOME/minimy/logs              # unmount log directory - and logs disappear
